'use clinet'

import Notification from '@/components/Notification'
import Navbar from '../components/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Personal Finance',
  description: 'Generated by create next app',
}
interface ToastProviderProps {
  children: React.ReactNode
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <Notification /> */}
        <Navbar />
        {children}
        <ToastContainer />
        {/* <Footer /> */}
      </body>
    </html>
  )
}
